FROM nginx
COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html
COPY addtime.html /usr/share/nginx/html
COPY login.html /usr/share/nginx/html
COPY newmeeting.html /usr/share/nginx/html
COPY signup.html /usr/share/nginx/html
COPY index_anna.js /usr/share/nginx/html
EXPOSE 80
EXPOSE 443